version: 1.0.{build}
os: Windows
clone_depth: 1

environment:
  JAVA_HOME: C:\\tools\\java\\zulu11

install:
  - ps: Install-Product node '14.17.3'
  - ps: choco install maven -y

build_script:
  - mvn clean package

test_script:
  - mvn test
