image: Ubuntu2204

stack: jdk 11

branches:
  only:
    - main

build: off

cache:
  - ~/.m2/repository -> pom.xml

before_build:
  - mvn -v
  # Исправленная строка: || true гарантирует успешный код выхода, даже если директории нет
  - find ~/.m2/repository -name "*.lastUpdated" -delete || true

build_script:
  - mvn clean package -DskipTests -U -B -Dmaven.resolver.transport=wagon -Dmaven.wagon.http.retryHandler.count=3

test_script:
  - mvn verify -U -B -Dmaven.resolver.transport=wagon -Dmaven.wagon.http.retryHandler.count=3
